### ISSUE TITLE
Latest version of CModulus.cpp compile error with NTL 9.10.0

### ISSUE THREAD

**Issue by umikachen** [shaih/HElib#100]
Hi, I just pulled the latest version of HElib, and when I was trying to build the source code with  NTL  9.10.0, I got the following errors. It seems that the class "PreconditionedRemainder" in NTL do not exist. Has anyone run into the same problem? thanks in advance
```
g++ -g -O2 -std=c++11 -pthread -DFHE_THREADS -DFHE_DCRT_THREADS  -c CModulus.cpp
CModulus.cpp: In member function ‘void Cmodulus::FFT(NTL::vec_long&, const NTL::ZZX&, long int) const’:
CModulus.cpp:200:5: error: ‘PreconditionedRemainder’ was not declared in this scope
     PreconditionedRemainder prem(zz_p::modulus(), sz);
     ^
CModulus.cpp:204:44: error: ‘prem’ was not declared in this scope
       tmp.rep[i].LoopHole() = prem(x.rep[i]);
                                            ^
Makefile:91: recipe for target 'CModulus.o' failed
make: *** [CModulus.o] Error 1
```

**Comment by shaih** [comment]
Sorry, just pushed a version of HElib which is compatible with the new NTL

**Comment by tran-tien-dat** [comment]
@shaih your latest commit deleted the Makefile though

**Comment by shaih** [comment]
oops, not sure what happened there. Added back the Makefile.

**Comment by umikachen** [comment]
Thanks a lot! I shall close this issue.
