### ISSUE TITLE
Assertion `ProbPrime(pp)' failed

### ISSUE THREAD

**Issue by cboubel** [shaih/HElib#114]
Hi, 

I have an issue with my code. It is a simple use of homomorphic encryption. I make the compilation without errors but when I try to execute my code, I have the following error : 

"PAlgebra::PAlgebra(long unsigned int, long unsigned int, const std::vector<long int>&, const std::vector<long int>&): Assertion `ProbPrime(pp)' failed" 

I checked the file but I don't know how to solve that. Anyone ? I specify that this code works on one computer and when I put it on another one (I'm using two computers), it failed.

Thanks in advance,

Christophe

**Comment by fionser** [comment]
the parameter `p` should be a prime number
