### ISSUE TITLE
Probably wrong implementation of replicate

### ISSUE THREAD

**Issue by fionser** [shaih/HElib#115]
I am studying the replicate functionality, and to my understand, 
here is a bug for the current implementation.

The following codes are from the `replicate.cpp`.
```
void replicate0(const EncryptedArray& ea, Ctxt& ctxt, long pos)
{
  long dim = ea.dimension();

  for (long d = 0; d < dim; d++) {
    if (!ea.nativeDimension(d)) {
      long shamt = -ea.coordinate(d, pos);
      ea.rotate1D(ctxt, d, shamt, true); // "don't care"
    }
```

The `if(!ea.nativeDimension(d))` statement only left-side rotates the non-nativeDimension ciphertexts;
so for the nativeDimension ciphertexts, the replication functionality might be wrong.

**Comment by victorshoup** [comment]
It would take me some time to investigate this.
I think it is probably OK.
The thing to do is try a test case.

**Comment by fionser** [comment]
@victorshoup , I am using the `m=16384, p=8191` parameters
so I have only one generator (`ea.dimension() == 1`) and `SameOrder(0)` is true.

**Comment by fionser** [comment]
@victorshoup 
It works fine!! the origin implementation is so clever!!
The reason I think it wrong, because I am implementing a replicate-like function
which just fills the first K slots instead of filling all the slots.
