### ISSUE TITLE
The noise estimation of Ctxt.h

### ISSUE THREAD

**Issue by fionser** [shaih/HElib#118]
I found the following codes in the `Line 146 of Ctxt.cpp`

```
double f = 0.0;
  for (long i=0; i<lsize(parts); i++) {
    // addPrimesAndScale returns the logarithm of the product of added primes,
    // all calls should return the same value = log(prod. of primes in setDiff)
    f = parts[i].addPrimesAndScale(setDiff);
  }
```

Should the `f` be the summation of the parts, that is
`f +=   parts[i].addPrimesAndScale(setDiff);`

Thx.

**Comment by victorshoup** [comment]
Huh.  That does look quite suspicious. 
Shai, what do you think?

**Comment by shaih** [comment]
No, it is not a bug and `f = ...` is correct.

Note the comment in this code, all calls to addPrimesAndScale return the same value, and we just assign that value to f and use it later on. It is being re-assigned every time, but that's okay.
