### ISSUE TITLE
Problems with linear maps evaluations for extension fields larger than 2^64

### ISSUE THREAD

**Issue by benjaminhmtan** [shaih/HElib#119]
In my use of HElib, I would like to evaluate linear maps on the encrypted messages, currently looking at around F_2^400-F_2^500 . The functionality works as expected for extension degrees less than 64 but fails once it goes beyond that. 

I found that in addition to the Frobenius matrices, some 1D matrices have to be generated to compute smartAutomorphism for large powers and wonder if using those are causing problems with linear map evaluations. Does anyone know why linear map evaluations fail for large extension degrees?

**Comment by ssmiler** [comment]
If I understand well your plaintext space is F_2^k for k>400? If this is the case HElib does not support plaintext spaces over 2^64 (or something near).

**Comment by fionser** [comment]
@ssmiler 2^50 for some machines and older version of NTLs, and 2^60 the lastest version.

**Comment by ssmiler** [comment]
@fionser I was too lazy to look the code :)
