### ISSUE TITLE
How to bootstrapping when p=17?

### ISSUE THREAD

**Issue by georgecsx** [shaih/HElib#123]
I have set p=17 and L=100 in Test_Bootstrapping, but it always shows "decryption error". I want to know how to solve this problem. Many thanks to you.

**Comment by shaih** [comment]
I don't know why that setting returns an error, I will try to find time to look at it but it may be a long while before I get to it.

**Comment by shaih** [comment]
bug fixed, it should work now

**Comment by georgecsx** [comment]
I tried it and it works very well. Thank you very much  Prof. Shai Halevi. I really appreciate it.
