### ISSUE TITLE
How the modulus swithing works with p2size?

### ISSUE THREAD

**Issue by HanKyoohyung** [shaih/HElib#130]
I have some questions about p2size while build modulus chain.

In HElib, p2size is used in buildmodchain and this part is different with a paper BGV12, they used only psize primes so the modulus q_i is prod_{j=0}^{i}p_j.

When we use p2size, build a mod-chain creates (p0,p1,...,p_{num-1}) with p0 is 22-bit prime and otherthings are 44-bit primes (suppose there are no special primes).

How the level of the scheme is about 2 * num - 1? If modulus switching (from p_i to p_i-1) accurs in every homomorphic multiplication, the level of the scheme looks like just 'num' not '2 * num - 1'.

Is there are any paper including this technique?

Thank you for reading

**Comment by shaih** [comment]
For odd levels i we use modulus $qi = p0* \prod_{j=1}^{(i-1)/2} p_{2j-1},$

while for even levels i we use $qi = \prod_{j=1}^{i/2} p_{2j-1}.$

When you switch from odd to even level you just drop p0, when you switch from even to odd level you add back p0 and drop the top pi.
