### ISSUE TITLE
Some perplexity with the "Level" parameter

### ISSUE THREAD

**Issue by datascale** [shaih/HElib#133]
Thank you for making this library available and this helpful forum. Please help me understand a few things associated with HElib "Levels".

1. Should not each ciphertext part be a _L by phi(m)_ matrix? Instead, the ciphertext parts are _L/2 by phi(m)_ matrices when output to a file. Is "Level" in the implementation actually _half_ the definition in literature?  

2. I am unable to perform multiplications and get correct results for _Levels_ lesser than _8_ with the setting _[security bits (k) = 80, and p=2, r = 32, d=1, c=3, w=64]_; _p_ and _r_ were picked to encrypt Long integers. However, the operation works like a charm for _L>=8_. Why is it not working for _L= 2_? Theoretically _L=2_ should support the first multiplication, isn't that right? 
(Note: For L=8, m=7781, and corresponding n_slots = 150 generated) 

- The story is consistent when I set a much lower _p^r=127_ (everything set the same except L and  _m_). I cannot get accurate multiplications even for something as small as _1*2=2_ with _L=2_. The operation succeeds with _L>=4_ and corresponding higher _m_. 

3. I tried computing the _runningSums( )_ of freshly encrypted ciphertext with the two setting sets above.  Surprisingly, the results are incorrect with _L=8_ in the former setting and _L=4_ in the latter one. I get accurate results only when I set a much higher _L=27_ for the former and _L=10_ for the latter. Why is this operation failing for lower _L_ ?

4. Finally, for a larger _p^r_ for example _p=2_ and _r=32_, are the parameters (_m_, _nslots_, etc.) generated and encryption plus the operations performed by the implementation still secure?

**Comment by fionser** [comment]
i might help for parts of your issues.
2. with p^r=2 the setting with L = 2 should support one multiplication 
3. the total sum method has a very deep relationship with the rotation method. And for some parameters the rotation method could introduce more noise resulting a noiser total sum. Thereby you need more level to compute it correctly. Finally the complexity of the total sum is log to the number of slots. More slots mean more homomorphic operations and thus more noise will be introduced
4 you can use FHEcontext::security-level() method to get an approximation of security

**Comment by datascale** [comment]
Thank you @fionser for your clear response.
