### ISSUE TITLE
Matrix/Vector Multiplication with HElib

### ISSUE THREAD

**Issue by datascale** [shaih/HElib#135]
The matrix-vector multiplication with a _column-major_ matrix is very well explained and the algorithm is practical as it requires _n_ replications only. As for with a _row-major_ matrix, the multiplication seems to be more complex. It is not well understood from literature how to "rearrange the entries of matrix _A_" or transpose it. Moreover, the suggested algorithm that uses the "transposition principle" considered to be better seems to actually require _n^2_ replications. 

1. What is/are the algorithm(s) to rearrange / transpose the entries in matrix _A_ so as to get a transpose of _A_ ?

2. How is it ( or is it?) the algorithm using "transposition principle" more practical than rearranging/transposing _A_ first, then computing the matrix-vector multiplication ? I could possibly figure this out myself if I knew 1.

Thank you.

**Comment by fionser** [comment]
1. For symmetric matrices, the row-major and column major is the same.
2. For general cases, we can use the `totalSum` routine in HElib. Take one element-wise multiplication
then totalSum all the entries.

**Comment by datascale** [comment]
Thank you for your response, @fionser. The reason I am refraining from totalSum is because of the extra "Levels" it needs to complete the computations.

**Comment by fionser** [comment]
@datascale Yes, there is no free lunch. Actually, the over head of "rotation" is pretty high for some parameters, `p` and `m`.

**Comment by datascale** [comment]
@fionser, Thank you for your response.
