### ISSUE TITLE
Multithreads with FHE_timer

### ISSUE THREAD

**Issue by fionser** [shaih/HElib#136]
Currently, I hit a situation that FHE_timer might crash when multithread is used.
(what a pity, I do not encounter this situation in the previous, and it just popped out.)

If you are facing  a similar situation, plz try to omit the macros in `timing.h`.

**Comment by Lawliar** [comment]
Hi @fionser ,I am also trying to multithread some functions i.e. the recrypt on my own using <thread> which C++ provides ,  but I encountered a segmentation fault when doing it. But I did not use FHE_timer in my code,meanwhile I noticed that some functions in helib have already used the BasicThreadPool that NTL provides, might this be the cause of the failure too? 
the important part of code may look like:
`void single_bootstrap(Ctxt & c,int num)
{
    cout <<"starting "<<num<<" level:"<<c.findBaseLevel()<<endl;
    FHEPubKey& pk = (FHEPubKey&) (c.getPubKey());
    pk.reCrypt(c);
    cout <<"ended "<<num<<"level:"<<c.findBaseLevel()<<endl;
}
//in main function 
// some initialization i.e. enable bootstrapping
Ctxt c0(publicKey), c1(publicKey);
  ea2.encrypt(c0, publicKey, p0);
  ea2.encrypt(c1, publicKey, p1);
  thread t1(single_bootstrap,std::ref(c0),0);
  thread t2(single_bootstrap,std::ref(c1),1);
  t1.join();
  t2.join();
`

**Comment by Lawliar** [comment]
oops, I have no idea why the code looked so unorganized

**Comment by AlexanderViand** [comment]
@Lawliar I assume you did, but just to make sure: 
Did you compile NTL with the options `NTL_THREADS=on`  and (optionally) `NTL_THREAD_BOOST=on`?
NTL by default/as described in the helib `INSTALL.txt` isn't threadsafe.

**Comment by Lawliar** [comment]
@AlexanderViand  Yeah,I noticed that, in order to enable multithread, the options you mentioned must be added when configuring NTL, And it worked for my problem.Thank you very much!

**Comment by fionser** [comment]
@AlexanderViand FHE_timer is anywhere in HElib. For instance, you can use printAllNamedTimers() to see what timers have been set inside the HElib.
