### ISSUE TITLE
why use Phi(m) divide ordP to get slot number?

### ISSUE THREAD

**Issue by NanXiao** [shaih/HElib#145]
Hi all,

I am reading `FindM()` source code, but confused the algorithm of getting slot number:  

```
static long ms[][4] = {  // pre-computed values of [phi(m),m,d]
      //phi(m), m, ord(2),c_m*1000 (not used anymore)
      { 1176,  1247, 28,  3736}, // gens=5(42)
      ......
    };
    for (i=0; i<sizeof(ms)/sizeof(long[4]); i++) { 
      if (ms[i][0] < N || GCD(p, ms[i][1]) != 1) continue;
      long ordP = multOrd(p, ms[i][1]);
      long nSlots = ms[i][0]/ordP;
      if (d != 0 && ordP % d != 0) continue;
      if (nSlots < s) continue;

      m = ms[i][1];
      break;
    }
```

I can't understand why use `Phi(m)` divide `ordP`? Is there special requirement of getting slot number?

Thanks very much in advance!

Best Regards
Nan Xiao

**Comment by fionser** [comment]
That is the mathematical reason. We recommend to read the paper. Fully Hommorphic SIMD operation.
