### ISSUE TITLE
HElib only using a single thread, even with threading options enabled

### ISSUE THREAD

**Issue by AlexanderViand** [shaih/HElib#147]
I'm using HElib with NTL/GMP. NTL has been compiled with threadsafe options (`./configure NTL_GMP_LIP=on NTL_THREADS=on NTL_THREAD_BOOST=on NTL_EXCEPTIONS=on`) and HElib has been compiled with `CFLAGS = -g -O2 -std=c++11 -pthread -DFHE_THREADS -DFHE_BOOT_THREADS -fmax-errors=2`

As I understand, this should not only make HElib threadsafe, but should already cause at the very least NTL to split its work among several threads. Nevertheless, I never see my programs use more than a single thread.

I've got a [docker image](https://hub.docker.com/r/alexanderviand/visual-studio-linux-build-box-with-helib/) for my development setup, and I've double checked the makefile/etc but maybe I've missed something else? My programs are compiled with `-pthread` as well.

Is there a way to query HElib for it's thread-support at runtime?

Thanks in advance!

**Comment by shaih** [comment]
Try to `make Test_General_x` (in the source directory) and then run `./Test_General_x nt=4` (say), this should run the standard HElib simple test with four threads.

Assuming this works, you just need to add a call to the NTL method `NTL::SetNumThreads(num)` somewhere in your main program, this should make some HElib routines use num threads when they are executed.

**Comment by AlexanderViand** [comment]
Thanks, adding a call to `NTL::SetNumThreads(...)` worked! 
(I never noticed that call in the examples, but now that you've mentioned it, it seems obvious)

**Comment by radwasherif** [comment]
I am getting this error whenever I call `NTL::SetNumThreads()` :
 `undefined reference to NTL::ResetThreadPool(NTL::BasicThreadPool*)' `

**Comment by victorshoup** [comment]
My guess is that the library was compiled with thread boosting off, but 
you are compiling client code with thread boosting on. You'll have to rebuild
the library with thread boosting on.

**Comment by radwasherif** [comment]
I already had NTL 10.5.0 installed. I recompiled it using `./configure NTL_GMP_LIP=on NTL_THREADS=on NTL_THREAD_BOOST=on NTL_EXCEPTIONS=on`, and the error persists. 
I have gcc version 4.9.3, could that be a problem? 
Should I remove the library completely and try again?
