### ISSUE TITLE
Maybe the bug in EncryptedArray's shift function

### ISSUE THREAD

**Issue by NanXiao** [shaih/HElib#148]
I write the following code to test `EncryptedArray`'s `rotate` and `shift` function:  

```
#include <iostream>

#include "FHE.h"
#include "FHEContext.h"
#include "EncryptedArray.h"

#include "NTL/ZZ.h"
#include "NTL/ZZX.h"

int main()
{
	unsigned long m = 11119, p = 2, r = 1;
	long L = 11;

	FHEcontext context(m, p, r);
	buildModChain(context, L);

	FHESecKey secretKey(context);
	secretKey.GenSecKey(64);
	addFrbMatrices(secretKey);
	addSome1DMatrices(secretKey);

	const EncryptedArray *ea = secretKey.getContext().ea;
	long slots = ea->size();

	Ctxt res(secretKey);
	
	for (auto i = 0; i < slots; i++)
	{
		std::vector<NTL::ZZX> vec(slots, NTL::ZZX(0));
		vec[0] = NTL::ZZX(1);
			
		Ctxt tmp(secretKey);
		ea->encrypt(tmp, secretKey, vec);
			
		ea->rotate(res, 1);
		res += tmp;
	}

	std::vector<NTL::ZZX> dec(slots, NTL::ZZX(0));
	ea->decrypt(res, secretKey, dec);
	for (auto &v : dec)
	{
		std::cout << v << std::endl;
	}

	return 0;
}
```

The running result fits my expectation (all is `NTL::ZZX(1)`):  

```
[1]
[1]
[1]
[1]
...
[1]
```

But after change
    

> ea->rotate(res, 1);

to 
> ea->shift(res, 1);

The running result seems messy:  

```
[0 0 1 0 1 1 0 1 1 0 1 1 1 1 0 1 1 1 1 1 1 0 0 0 1 0 1 0 0 1 1 0 1 0 1 0 1 0 1 0 0 0 1 1 0 1 0 1 1 1]
[1 0 1 0 1 1 1 1 1 0 0 0 0 0 1 0 0 1 1 1 0 1 1 1 0 0 0 1 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 1 1]
[0 0 1 0 1 0 0 1 1 0 0 1 1 0 1 1 0 1 1 1 0 0 0 1 0 0 0 0 0 0 0 1 1 0 0 0 1 1 1 0 1 1 1 0 0 0 0 0 1 1 1]
[1 0 1 1 0 0 0 1 1 0 0 0 1 0 0 0 1 0 0 1 1 0 1 1 1 1 0 0 1 0 0 0 0 0 0 0 0 0 1 0 1 1 1 0 0 0 0 1 1 1]
[0 0 0 0 1 1 0 0 1 1 1 0 1 1 0 0 1 0 1 0 0 0 0 0 0 0 0 1 0 1 1 1 0 1 0 0 1 1 0 0 1 1 0 0 1 0 1 0 0 0 1]
....
```

Is there a bug in `shift`? Or I misuse `shift` function? Thanks in advance!

Best Regards
Nan Xiao

**Comment by fionser** [comment]
@NanXiao  check "Ctxt:isCorrect()", the decryption might fail already.

**Comment by NanXiao** [comment]
@fionser I can check it. But by the way, is there any error of using shift operation? I am a little confused, thanks very much!

**Comment by fionser** [comment]
@NanXiao The complexity of shift is larger than rotation. So, the noise in the ciphers might just grows too much, resulting the decryption failure. The usage of shift is fine.

**Comment by NanXiao** [comment]
@fionser Thanks very much for your comments!

I use `Ctxt::isCorrect()` to check the `Ctxt` state, and find after rotate `slots` times, the `Ctxt` is still good, while after shirt `slots` times, the `Ctxt` is already bad.

So for the specified/const parameters and data, after rotating `slots` times, the `Ctxt` can always be correct or not?  Or it may change?

Thanks!

**Comment by fionser** [comment]
@NanXiao The answer is yes. 

You should first understand that the current FHE works on the idea of "circuit".
The parameter "L" indicates how much level of "homomorphism" you can use.
Second, different operations consume the different amount of "homomorpihsm" you set from the beginning.

So, we need to make sure how much "hommorphism" you need to use, and then to find the right parameters. Any operations that consume too much, will result at bad ciphertexts.

**Comment by NanXiao** [comment]
@fionser Got it! Thanks very much for your time and detailed explanation!
