### ISSUE TITLE
Error after setting shortcut = true in extractDigits 

### ISSUE THREAD

**Issue by haochenuw** [shaih/HElib#149]
I changed line 94 in Test_extractDigits.cpp  to 
``  extractDigits(digits, c, true); ``
and called it with 
` ./Test_extractDigits_x m=10000
`
Then I got the error message: 

> m=10000, p=3, r=3, L=14
> number of slots = 8
> plaintext=[24 9 12 25 7 17 23 0]
> extracting 3 digits... done
> 0th digit=[24 9 12 25 7 17 23 0]
>  error: v[0]=24 but 0th digit comes 24 rather than 0

Can someone explain what I did wrong here?

**Comment by NanXiao** [comment]
According to [extractDigits](https://github.com/shaih/HElib/blob/533ad3982379a5cab73162818a7dc88a90fd4e49/src/extractDigits.cpp#L35) declaration:  

> void extractDigits(vector<Ctxt>& digits, const Ctxt& c, long r, bool shortCut)

The third parameter should be `r`, so I think your intention may be:  

`extractDigits(digits, c, r, true);`

**Comment by haochenuw** [comment]
Thanks for pointing it out! However after I changed it  the problem remains 
Again I changed line 94 in Test_extractDigits.cpp to
> extractDigits(digits, c, 3, true);

and this time I got
> $./Test_extractDigits_x
m=11243, p=3, r=3, L=14
number of slots = 154
extracting 3 digits... done
 error: v[0]=4 but 0th digit comes 4 rather than 1

**Comment by haochenuw** [comment]
I figured it out. There are two optional parameters r and shortcut.

**Comment by haochenuw** [comment]
Can any one help?

**Comment by shaih** [comment]
Looks like a bug, I will try to find time to look at it, hopefully sometime this month.

**Comment by shaih** [comment]
Should be fixed now. Note that when calling extractDigits with shortCut=true, all the digits are returned with respect to plaintext space mod p (rather than mod p^e for e>1, as could happen when this flag is false)
