### ISSUE TITLE
The problem of summing the value of every slot in Ctxt.

### ISSUE THREAD

**Issue by NanXiao** [shaih/HElib#155]
I want to sum the value of every slot in `Ctxt`. Now the method I can get is like this:  

a) multiple original `Ctxt` with a temporary `Ctxt` who has `1` at the first slot and other slots filled with `0` , and store the result into another `Ctxt`;  
b) left-rotate the original `Ctxt` to use `a)` method to store the second slot value of original `Ctxt` into  another `Ctxt`;
......
c) So if the `Ctxt` has `10` slots, I will finally get `10` new `Ctxt`s which has only value in the first slot, then add `10 Ctxts`.  

Is there any more simpler method? Thanks very much in advance!

Best Regards
Nan Xiao

**Comment by ssmiler** [comment]
There's a method in HElib which sums up all the slot values.
If not you can omit step a in your algorithm.

**Comment by shaih** [comment]
See the `runningSums` and `TotalSums` functions in `Encryptedarray.h`. They are documented in the Halevi-Shoup paper from CRYPTO 2014.

**Comment by fionser** [comment]
@NanXiao I strongly recommend you to firstly skim the design-document in the repository. You can just skip the math and have an image about what HElib can do.
