### ISSUE TITLE
FHEcontext::securityLevel()

### ISSUE THREAD

**Issue by JoFLV** [shaih/HElib#159]
Hi all,

what does it mean when `FHEcontext::securityLevel()` returns a negative value?
Can anyone guide?

Regards & Thanks in advance

**Comment by fionser** [comment]
The securityLevel is somehow an estimation. When you use too small `m` or too large `L`.
It might return a negative value.

**Comment by JoFLV** [comment]
I have checked the code. Looks like the approximation is (as you mentioned) is for small m inprecise.
Thanks for your answer !
