### ISSUE TITLE
Choosing bootstrapping parameters

### ISSUE THREAD

**Issue by radwasherif** [shaih/HElib#161]
Is there a simple explanation for how the parameters of a bootstrappable instance are computed?

**Comment by shaih** [comment]
There is aparams.cpp program there, you can `make params_x` and then run it to get suggested parameters for bootstrapping.

**Comment by haochenuw** [comment]
Hmm...I couldn't find aparams.cpp in the repository.

**Comment by shaih** [comment]
typo, it is params.cpp, without the a
