### ISSUE TITLE
Parallelization with OpenMP. 

### ISSUE THREAD

**Issue by radwasherif** [shaih/HElib#163]
Would HElib run properly if parallelized with the OpenMP library?

**Comment by fionser** [comment]
You need to set the correct flag when you compile NTL and HElib.
* NTL_THREADS=on (is supported since versions 7.0)
* #CFLAGS = -g -O2 -std=c++11 -pthread -DFHE_THREADS -DFHE_BOOT_THREADS -fmax-errors=2

Also, you need to use c++ compile that supports openMP

**Comment by radwasherif** [comment]
I've tried calling NTL::SetNumThreads() (as in #147 ) in my program but I keep getting an error that it's not a member of NTL.

**Comment by fionser** [comment]
Update your NTL to the newest version, and have a try again.
