### ISSUE TITLE
Encoding real numbers 

### ISSUE THREAD

**Issue by radwasherif** [shaih/HElib#165]
Is there a way to perform computations on real numbers (not just integers) in HElib?

**Comment by MikeS159** [comment]
Try flt2int_encode from here:
https://github.com/bristolcrypto/HEAT/tree/master/HElib-api

**Comment by radwasherif** [comment]
@MikeS159 Thank you very much. But can this be used along with ciphertext packing, given that the output is a polynomial?

**Comment by radwasherif** [comment]
@MikeS159 Thank you, I've checked it out. Can you maybe give me an example on how to use it? It's working on it's own but with HElib it doesn't give correct results.

**Comment by MikeS159** [comment]
This might actually be to application specific. It encodes floating point numbers to a balanced base 3 polynomial representation. This might not work for you.

**Comment by radwasherif** [comment]
Okay, thanks.
