### ISSUE TITLE
Related Materials (Codebase non-specific)

### ISSUE THREAD

**Issue by robogen** [shaih/HElib#168]
Apologies if this is the wrong place for this question, but after a course I took where I made use of this library, I'm fascinated and interested in learning more. It's pretty difficult to find a Number Theory course though, or when its available the time slot doesn't work for other required courses. 

Could you link materials/resources helpful in self-education of Number Theory with the goal of better understanding the background of Homomorphic Encryption? Thanks for any help!

**Comment by TomMD** [comment]
Shoup's number theory book and eprint will be key resources, I expect.  Also, this question should go to a web forum, like crypto.stackexchange.com or quora, instead of on a project issue tracker.

**Comment by robogen** [comment]
Thank you, and good point on crypto.stackexchange.com, I forgot that was a thing embarrassingly enough!
