### ISSUE TITLE
Strange output in boolean circuit complements

### ISSUE THREAD

**Issue by chack1996** [shaih/HElib#169]
I am not a native English speaker, so sorry for my grammer mistake. I met a strange problem while trying to complete different kinds of calculations with boolean circuit. Here is the code ( I had simplify it ):
       
`

        #include <NTL/ZZ.h>
	#include <NTL/BasicThreadPool.h>
	#include "FHE.h"
	#include "timing.h"
	#include "EncryptedArray.h"
	#include <NTL/lzz_pXFactoring.h>
	#include <cassert>
	#include <cstdio>
	#include <iostream>
	using namespace std;
	ZZX CtxtToZZX(Ctxt & ctxt, FHESecKey & secretKey)
	{
		ZZX temp;
		secretKey.Decrypt(temp, ctxt);
		return temp;
	}
	int main()
	{
		cout<<"publicKey and secretKey generating..."<<endl;
		FHEcontext * context;
		FHESecKey * secretKey;
		const FHEPubKey * publickey;

		long p = 2;
		long r = 1;
		long L = 16;
		long c = 3;
		long w = 64;
		long d = 0;
		long k = 128;
		long s = 0;

		long m = FindM(k, L, c, p, d, s, 0);

		unsigned bits= 2;

		context = new FHEcontext(m, p, r);
		buildModChain(*context, L, c);

		ZZX G = context->alMod.getFactorsOverZZ()[0];

		secretKey= new FHESecKey(*context);
		publickey = secretKey;
		secretKey->GenSecKey(w);

		cout<<"Key generation done"<<endl;
		
		Ctxt zero(*publickey);
		publickey->Encrypt(zero, to_ZZX(0));
		vector<Ctxt> c1(15, zero);
		vector<Ctxt> c2(15, zero);
		vector<Ctxt> result(15, zero);
		Ctxt carry(*publickey);
		publickey->Encrypt(carry, to_ZZX(0));
		for(int i=0; i<15; i++)
		{
			cout<<"before"<<endl;
			cout<<"c1["<<i<<"]\t\t"<<CtxtToZZX(c1[i], *secretKey)<<endl;
			cout<<"c2["<<i<<"]\t\t"<<CtxtToZZX(c2[i], *secretKey)<<endl;
			cout<<"result["<<i<<"]\t\t"<<CtxtToZZX(result[i], *secretKey)<<endl;
			cout<<"carry\t\t"<<CtxtToZZX(carry, *secretKey)<<endl;
			
			result[i]+=c1[i];
			result[i]+=c2[i];
			result[i]+=carry;
			carry *= c1[i];// + b.ctxts[i]);
			
			cout<<"after"<<endl;
			cout<<"result["<<i<<"]\t\t"<<CtxtToZZX(result[i], *secretKey)<<endl;
			cout<<"carry\t\t"<<CtxtToZZX(carry, *secretKey)<<endl;
		}
		return 0;
	}`
from the 14th time, I cannot understand the output. Both result[i] and carry are not 0 as I expect, just as how boolean circuit works. I know maybe this is not a right place to ask such a question, but it puzzled me for a few days. Did I do something wrong?

**Comment by chack1996** [comment]
Sorry I am new to this field, and it is a stupid question. The problem of the program is that L, which limits the depth of circuit is too small. I don't know much about its principle, maybe something like noise. Maybe I need to read something about HE algorithm.

**Comment by AlexanderViand** [comment]
Try using `multBy` instead of `*=`. The former does something called relinearization, which is required to prevent noise blow-up. Without this, you might need a very large L, with it your L (or similar) should work.

**Comment by chack1996** [comment]
@AlexanderViand Thanks for your help. I will read the document carefully.
