### ISSUE TITLE
Is it possible for HElib implements the Full Residue Number System ?

### ISSUE THREAD

**Issue by fionser** [shaih/HElib#189]
Full RNS described in [this](https://link.springer.com/chapter/10.1007/978-3-319-69453-5_23) paper.
Is it possible for HElib to use this to avoid CRT-Poly switching, and keep staying in the CRT representation as much as possible ?

**Comment by shaih** [comment]
There are accually easier/better ways to do "full RNS", see [here](https://eprint.iacr.org/2018/117). Many of these techniques are implemented in HElib, but it does *not* help to avoid the expensive translations back and forth between DoubleCRT and coefficient representation. These techniques handle the integer CRT part, the hard part is the polynomial CRT.
