### ISSUE TITLE
Homomorphic Evaluation of the AES Circuit

### ISSUE THREAD

**Issue by Jenifer-l** [shaih/HElib#20]
Is it possible that your AES test to be placed here?
http://eprint.iacr.org/2012/099

**Comment by JeanPhilipe** [comment]
Amazing work..but i would like to find the directory src/aes i'm working on in my studies.
Thank you.

**Comment by shaih** [comment]
You need to checkout the aes branch, if you have a recent enough version of git then just use
`% git pull;  git checkout aes`
