### ISSUE TITLE
What value can I use to set the parameter "bitPerLevel"?

### ISSUE THREAD

**Issue by Jyun-Neng** [shaih/HElib#205]
I know that the equation of security level is ```k = 7.2*phim/bitsize -110```. The smaller bit size of the product of all primes, the larger security level is.

In Test_AES.cpp, ```bitPerLevel=23```.  
Why 23? Can I use smaller value than 23? (e.g. ```bitPerLevel=16```)

Using smaller ```bitPerLevel```, I can increase the number of levels. Meanwhile, the security level will not decrease too much. (Compare to increase the number of levels without using smaller ```bitPerLevel```)

If I want the security level to be large enough and so is the number of levels ```L```, I think that decreasing the ```bitPerLevel``` may be a choice. But I don't know what the smallest value can I use.

**Comment by shaih** [comment]
You can sometime decrease `bitsPerLevel`, but only upto a point. This is supposed to compensate at least for the added noise in a single multiplication, if you decrease it below some point you will notice that the same computation is now "eating" many more levels.

There is no good way in HElib currently to tell you what's the best value for this, it depends on the computation that you want to make and the other parameters. You can try to experiment with it until you find the best value.

Another lever to try and pull is the value of `c` in (number of digits) in the call to `buildModChain`, `c=3` works reasonably well, but sometimes you can get some mileage out of setting it to 4 or 5 (rarely maybe even 6).

If you really want to go crazy, there is a constant hard-wired on line 473 in Ctxt.cpp

`double noiseThreshold = log(modSwitchAddedNoiseVar())*0.55;`

Changing 0.55 to something else (e.g. 0.5) has some random effects on when HElib does modulus switching, this can sometimes (very rarely) result is much better utilization of levels.
