### ISSUE TITLE
Any math materials about the buildLinPolyCoeffs in EncryptedArray  ? 

### ISSUE THREAD

**Issue by fionser** [shaih/HElib#206]
@shaih :)
* Is there any math materials about why the `buildLinPolyCoeffs` work ?
* Is still confusing what `intraSlots.cpp` is doing and why it work.

Thanks

**Comment by fionser** [comment]
Actually, why not encode the coefficient vectors inside `buildLinPolyCoeffs`, but encode it in the `applyLinPoly*` functions ?
* IMHO, the following pieces of code in the `applyLinPoly1` function in `EncryptedArray.cpp` can be just computed once and reused for many times. We can move these codes in `buildLinPolyCoeffs`, we should save many computation time for multiple calls of `applyLinPoly1`
```
for (long j = 0; j < d; j++) {
    vector<ZZX> v(nslots); // all the slots of v equal C[j]
    for (long i = 0; i < nslots; i++) v[i] = C[j];
    ea.encode(encodedC[j], v);
  }
```

**Comment by victorshoup** [comment]
There are anyway plans to harmonize these interfaces with the matmul interfaces, and to also improve the algorithms as well.

**Comment by fionser** [comment]
thanks.
