### ISSUE TITLE
Custom generators for the quotient group Z_m^*/<p>

### ISSUE THREAD

**Issue by deevashwer** [shaih/HElib#211]
Can we have a custom set of generators to the quotient group Z_m^*/\<p\>?
So, there are more than 1 generating sets of this group.
If I input a different set than the one generated by HElib for that group to FHEcontext, will everything work just as seamlessly?

**Comment by shaih** [comment]
The constructor for `FHEcontext` takes a vector of generators (and a vector of their orders), so you can use whatever generators you want. It does not check that these generators and orders are correct, so things could go up in flames if you give it invalid vectors.

If you do not supply these vectors (or if the sizes of the two vectors are not the same) then it will compute its own set of generator. You can see some examples in the Test programs e.g.

`  ./Test_General_x mvec="[7 3 221]" gens="[3979 3095 3760]" ords="[6 2 -8]"
`

**Comment by deevashwer** [comment]
Thank you, @shaih. I got the answer I needed.
