### ISSUE TITLE
check_bootstrapping fails

### ISSUE THREAD

**Issue by AlexanderViand** [shaih/HElib#228]
`make check_bootstrapping`:
````
HElib requires NTL version 10.0.0 or higher, see http://shoup.net/ntl
If you get compilation errors, try to add/remove -std=c++11 in Makefile

./Test_bootstrapping_x noPrint=1 N=512
**error: original z[0]=-22396, p^r=2, p^e=64
z' = z - 0*q = -22396
z''=z' +0*p^r +-2*p^r*q = -32772
make: *** [check_bootstrapping] Error 1
````

`make check_ThinkBootstrapping`:
````
HElib requires NTL version 10.0.0 or higher, see http://shoup.net/ntl
If you get compilation errors, try to add/remove -std=c++11 in Makefile

./Test_ThinBootstrapping_x noPrint=1 N=512
**error: original z[7]=5253, p^r=2, p^e=64
z' = z - 1*q = -2940
z''=z' +0*p^r +-2*p^r*q = -32772
make: *** [check_ThinBootstrapping] Error 1
````
MacOS, using gcc 8.1.0, GMP 6.1.2 and NTL 11.2.0

Fresh install of HElib, got the bootstrapping error when running `make check`. Above is the output from running just the two failing checks for brevity. All other checks pass.

**Comment by mishrag324** [comment]
I have the same problem

**Comment by AlexanderViand** [comment]
I get the same errors on Ubuntu 18.04 using gcc 7.3.0, GMP 6.1.2 and NTL 11.2.0.  
`make check` shows no errors in GMP and NTL.

**Comment by jangsa** [comment]
I've got a similar failure on the same environment with @AlexanderViand 

`
g++ -g -O2 -std=c++11 -pthread -DFHE_THREADS -DFHE_BOOT_THREADS -fmax-errors=2 -o Test_bootstrapping_x Test_bootstrapping.cpp fhe.a -L/usr/local/lib -lntl -lgmp -lm
./Test_bootstrapping_x noPrint=1 N=512
**error: original z[18]=-2747, p^r=2, p^e=64
z' = z - 1*q = -10940
z''=z' +0*p^r +-2*p^r*q = -32772
Makefile:99: recipe for target 'check_bootstrapping' failed
make[1]: *** [check_bootstrapping] Error 1
make[1]: Leaving directory '/home/test/coding/c++/HElib/src'
Makefile:57: recipe for target 'check' failed
make: *** [check] Error 2
`

**Comment by victorshoup** [comment]
The problem was actually a bug introduced in NTL 11.2.0.
I just uploaded NTL 11.2.1 to www.shoup.net, which fixes the bug.

**Comment by jangsa** [comment]
@victorshoup 
Thank you! NTL 11.2.0 looks working fine.
Now I got "No rule to make target 'check_Test_Bin_IO_x'."
Actually "check_Test_Bin_IO_x" is not present at "src" directory.
```
g++ -g -O2 -std=c++11 -pthread -DFHE_THREADS -DFHE_BOOT_THREADS -fmax-errors=2 -o Test_tableLookup_x Test_tableLookup.cpp fhe.a -L/usr/local/lib -lntl -lgmp -lm
./Test_tableLookup_x
  *** testLookup PASS ***
  *** testWritein PASS ***
make[1]: Leaving directory '/home/test/coding/c++/HElib/src'
make check_Test_Bin_IO_x
make[1]: Entering directory '/home/test/coding/c++/HElib/src'
HElib requires NTL version 10.0.0 or higher, see http://shoup.net/ntl
If you get compilation errors, try to add/remove -std=c++11 in Makefile

make[1]: *** No rule to make target 'check_Test_Bin_IO_x'.  Stop.
make[1]: Leaving directory '/home/test/coding/c++/HElib/src'
Makefile:57: recipe for target 'check' failed
make: *** [check] Error 2
```

**Comment by jangsa** [comment]
@victorshoup 
Thank you!
It looks woking fine with NTL 11.2.0.
Still following occurs, so please accept [my pull request](https://github.com/shaih/HElib/pull/233)
```
./Test_tableLookup_x
  *** testLookup PASS ***
  *** testWritein PASS ***
make[1]: Leaving directory '/home/test/coding/c++/HElib/src'
make check_Test_Bin_IO_x
make[1]: Entering directory '/home/test/coding/c++/HElib/src'
HElib requires NTL version 10.0.0 or higher, see http://shoup.net/ntl
If you get compilation errors, try to add/remove -std=c++11 in Makefile

make[1]: *** No rule to make target 'check_Test_Bin_IO_x'.  Stop.
make[1]: Leaving directory '/home/test/coding/c++/HElib/src'
Makefile:57: recipe for target 'check' failed
make: *** [check] Error 2
```

**Comment by AlexanderViand** [comment]
Thanks @victorshoup for the NTL fix, both bootstrapping tests passed with NTL 11.2.1
