### ISSUE TITLE
Is it possible to determine secret key using context?

### ISSUE THREAD

**Issue by AbhishekNalamothu** [shaih/HElib#239]
I am building client and server model. Here, client generates key pair. Client shares his public key, m ,p,r values with server (As far as I understood, those 4 are the required for encryption, please tell me if I am wrong). In this process of sharing, is it possible to determine secret key using different w values in the following line. ```secretKey.GenSecKey(w);```

**Comment by shaih** [comment]
> I am building client and server model. Here, client generates key pair. Client shares his public key, m ,p,r values with server (As far as I understood, those 4 are the required for encryption, please tell me if I am wrong).

Client must send the context (not just m,p,r), then public key.

> In this process of sharing, is it possible to determine secret key using different w values in the following line. `secretKey.GenSecKey(w);`

I don't understand the question.

Calling `skey.GenSecKey(w)` will generate a new random secret-key polynomial. (A single `FHESecretKey` object can have many of them.) This has nothing to do with other secret-key polynomials that already exist. Having more than one secret-key polynomial is only useful for specialized applications, it is unlikely that you will need it.

**Comment by AbhishekNalamothu** [comment]
Sorry for unclear question. Let me explain the problem clearly.
Problem - matching between client and server data.
Requirement-  **Client and server are not allowed to see each others data**. Client can query server(client also shares it's encrypted data), and server executes operations (between it's encrypted data and client's encrypted data), and gives results back (in encrypted form) to client. Using secret key, client will decrypt the results.  
Solution (that I am thinking)- 
**client side** 
1.  Generate the key pair at client side, and store public key and private key in different files.
2.  Encrypt the client data with public key, and share the client's encrypted data, public key, m,p,r,and G with the server.  (I am able to store context in a file, but unable to read it back from file. That is why I am planning to share m,p,r,G. So that client will generate context, encrypted array object ```ea```).

 **Server side** 
3. Using m,p,r,G - server generates context and ea. Then, using public key, server encrypts it's data, and executes operations between client's and server data. Server shares its results back to client.

**client side** 
4. Using secret key (from file), it will decrypt the results. 

client side 
```   
    long m =aa, p = bb, r = cc;  
    // Native plaintext space r=1,  Computations will be 'modulo p'
    long L = dd; // Levels 
    long c = ee; // Columns in key switching matrix
    long w = ff; // Hamming weight of secret key
    long d = gg;
    long slb=hh;  //Slots Lower Bound : minimum number of slots 
    long security = ii; // security parameter 
    ZZX G;
    m = FindM(security, L, c, p, d, slb, 0);
    FHEcontext context(m, p, r);
    buildModChain(context, L, c);
    G = context.alMod.getFactorsOverZZ()[0];

    //key generation
    FHESecKey secretKey(context);
    const FHEPubKey& publicKey = secretKey;
    secretKey.GenSecKey(w);
    EncryptedArray ea(context, G);
    vector<long> vsample;
    for (int i = 0; i < ea.size(); i++) {
		
        vsample.push_back(1);
    }
   Ctxt ct1(publicKey);
   ea.encrypt(ct1, publicKey, vsample);
 // after above steps, I will store m, p, r, G values in a file, and public key,secret key,and ct1 in separate files. 
```
Server side 
```
ZZX G;
FHEcontext context(m, p, r); 
G = context.alMod.getFactorsOverZZ()[0];
FHEPubKey publicKey1(context);
EncryptedArray ea(context, G);
publickeyfile>>publicKey1;  // reading public key from file.
vector<long> vsample1;
for (int i = 0; i < ea.size(); i++) {
		
        vsample1.push_back(1);
    }
Ctxt ct2(publicKey1);
ea.encrypt(ct2, publicKey1, vsample1);
ctxtfile>>ct1; // reading client's encrypted data from file.
ct1+=ct2; // sample computation
//store ct1 in a file 
```
client side 
```
        ctxtfile >>ctr; // reading encrypted results from file
        secfile>>secretKey; // reading secret key from file
       vector<long> decsam;
	ea.decrypt(ctr, secretKey, decsam);
	cout<<decsam<<endl;
```
I would like to know, whether I am giving any chance to server to decrypt the client's data by passing m,p,r,G.  

Thank you so much.

**Comment by shaih** [comment]
Have a look at `Test_IO.cpp` and/or `Test_Bin_IO.cpp` to see how to send the context from client to server.

> I would like to know, whether I am giving any chance to server to decrypt the client's data by passing m,p,r,G.

No.

**Comment by AbhishekNalamothu** [comment]
Thank you!!

**Comment by AbhishekNalamothu** [comment]
requirement- **Client and server are not allowed to see each others data.**
Actually, I created following four programs. I would like to know is there any thing wrong with the execution of these programs. Because, I am not supposed to determine the secret key and decrypt the results on server side by executing Sk_deteremining.cpp(4 th program). 
**Client_side**
1. **client_sample_kg.cpp** - key pair generation, this program stores context, public key, secret key, and client encrypted data in separate files.
```
#include "FHE.h"
#include "EncryptedArray.h"


int main() {
	
    long m =0, p = 2, r = 1; // Native plaintext space
    // Computations will be 'modulo p'
    long L = 15; // Levels 
    long c = 3; // Columns in key switching matrix
    long w = 80; // Hamming weight of secret key
    long d = 0;
	long slb=0;  //Slots Lower Bound : minimum number of slots 
    long security = 62; // security parameter , number is directly proportional to the security.  
    ZZX G;
    m = FindM(security, L, c, p, d, slb, 0);
    FHEcontext context(m, p, r);
    buildModChain(context, L, c);
    G = context.alMod.getFactorsOverZZ()[0];

    //key generation
    FHESecKey secretKey(context);
    const FHEPubKey& publicKey = secretKey;
    secretKey.GenSecKey(w);
    EncryptedArray ea(context, G);
	
   //storing public key in file
    ofstream myfile;
     myfile.open ("~your path/HElib-master/src/public_key.txt");
     myfile <<publicKey;
     myfile.close();
	
    //storing secret key in file	
    ofstream myfile1;
     myfile1.open ("~your path/HElib-master/src/secret_key.txt");
     myfile1 <<secretKey;
     myfile1.close();
	
    //storing context in file	
    ofstream myfile3;
     myfile3.open ("~your path/HElib-master/src/Context.txt");
     myfile3 <<context;
     myfile3.close();
	
   //client data	
   vector<long> v2;
    for (int i = 0; i < ea.size(); i++) {
        v2.push_back(1);
    }
   cout<<v2<<endl;
   Ctxt ct1(publicKey);
    ea.encrypt(ct1, publicKey, v2);
	
   //storing encrypted client data in file
    ofstream myfile2;
    myfile2.open ("~your path/HElib-master/src/client_data.txt");
    myfile2 <<ct1;
    myfile2.close();
	 
	}
```
**Server_side**

 2. **server_sample.cpp** - read context, public key, and client's data from files. Using public key, server encrypts its data. Finally, server executes computation (xor in this case) and store result. 
```
#include "FHE.h"
#include "EncryptedArray.h"


int main() {
  long m =13981, p = 2, r = 1;
  ZZX G;  
  FHEcontext context(m, p, r);

  // reading context from file
  ifstream infile2; 
  infile2.open("~your path/HElib-master/src/Context.txt"); 
  infile2 >> context;  
  infile2.close();

  G = context.alMod.getFactorsOverZZ()[0];
  FHEPubKey publicKey(context);
  EncryptedArray ea(context,G);

  // reading public key from file
  ifstream infile; 
  infile.open("~your path/HElib-master/src/public_key.txt"); 
  infile >> publicKey;  
  infile.close();

  Ctxt ct1(publicKey);

  // reading clients encrypted data from file
  ifstream infile1; 
  infile1.open("~your path/HElib-master/src/client_data.txt"); 
  infile1>>ct1;
  infile1.close();

 //server data  
  vector<long> v2;
  for (int i = 0; i < ea.size(); i++) {
        v2.push_back(1);
    }
  cout<<v2<<endl;
  Ctxt ct2(publicKey);
  ea.encrypt(ct2, publicKey, v2);
 //xor computation
  ct1+=ct2;

 //storing xor results in file  
  ofstream myfile;
  myfile.open ("~your path/HElib-master/src/xor_results.txt");
  myfile <<ct1;
  myfile.close();
	
 }
```
**Client_side**

3. **client_decryption.cpp** - read context, public key, secret key, and results (from server side) from files. Decrypt the results.
```
#include "FHE.h"
#include "EncryptedArray.h"
int main(){
  long m =13981, p = 2, r = 1;
  ZZX G;  
  FHEcontext context(m, p, r);
  // reading context from file
  ifstream infile2; 
  infile2.open("~your path/HElib-master/src/Context.txt"); 
  infile2 >> context;  
  infile2.close();

  G = context.alMod.getFactorsOverZZ()[0];
  FHESecKey secretKey(context);
  FHEPubKey publicKey(context);
  EncryptedArray ea(context,G);
  
  // reading public key from file
  ifstream infile; 
  infile.open("~your path/HElib-master/src/public_key.txt"); 
  infile >> publicKey;  
  infile.close();
  
  // reading secret key from file  
  ifstream infile1; 
  infile1.open("~your path/HElib-master/src/secret_key.txt"); 
  infile1 >> secretKey;  
  infile1.close();
  Ctxt ct1(publicKey);
  
 // reading xor results from file    
  ifstream myfile1; 
  myfile1.open("~your path/HElib-master/src/xor_results.txt"); 
  myfile1>>ct1;
  myfile1.close();

 //decrypting  
  vector<long> dec;			
  ea.decrypt(ct1, secretKey, dec);
  cout<<dec<<endl;
}
```

**Server_side**

4. **Sk_determining.cpp** -  read context, public key, and results (stored in server side) from files. _Create a secret key by trying different hamming weights_ in ```secretKey.GenSecKey(w);``` 
```
#include "FHE.h"
#include "EncryptedArray.h"


int main() {
  long m =13981, p = 2, r = 1,w;
  ZZX G;  
  FHEcontext context(m, p, r);
  // reading context from file
  ifstream infile2; 
  infile2.open("~your path/HElib-master/src/Context.txt"); 
  infile2 >> context;  
  infile2.close();

  G = context.alMod.getFactorsOverZZ()[0];
  FHEPubKey publicKey(context);
  FHESecKey secretKey(context);
  secretKey.GenSecKey(w); /* <---- brute force attack : Trying different hamming weight will gives us secret key. At w=80 , the attacker finds the secret key*/
  EncryptedArray ea(context,G);

  // reading public key from file
  ifstream infile; 
  infile.open("~your path/HElib-master/src/public_key.txt"); 
  infile >> publicKey;  
  infile.close();

  Ctxt ct1(publicKey);
  
  // reading xor results from file
  ifstream infile1; 
  infile1.open("~your path/HElib-master/src/xor_results.txt"); 
  infile1>>ct1;
  infile1.close();
  
  //decrypting
  vector<long> dec;
  ea.decrypt(ct1, secretKey, dec);
  cout<<dec<<endl;
}
```


**Note** 
```
To avoid errors, I commented Ctxt.cpp 636 line ( Sanity check: same context and public key),NumbTh.cpp 868 to 872 lines (seekPastChar error). 
```

Thank you so much.

**Comment by shaih** [comment]
You need to initialize the random state at the client, otherwise the secret key will be predictable by the server. Before calling `secretKey.GenSecKey(w);`, you need to do something like this:
```
// Get a random number from whatever random source you have: /dev/random, 
// /dev/urandom, input by the user from the command line, or whatever
ZZ seed = ... ;
NTL::SetSeed(seed);

// Now you can choose an unpredictable secret key
secretKey.GenSecKey(w);
```
Then the server will not be able to recover the secret key. Note that the `w` parameter to `GenSecKey` is **not** random, this is just the intended "size" of the secret key

**Comment by AbhishekNalamothu** [comment]
Thank you so much for the immediate response!!
Please correct me if I am wrong. I added SetSeed to my client side key generation program - **client_sample_kg.cpp**, and gave value from the command line. After doing all of this,  I am still able to determine the secret key by executing **Sk_determining.cpp.**
Here is the program of client side key generation after changes.
**client_sample_kg.cpp(after chnages)**
```
#include "FHE.h"
#include "EncryptedArray.h"


int main() {
	
    long m =0, p = 2, r = 1; // Native plaintext space
    // Computations will be 'modulo p'
    long L = 15; // Levels 
    long c = 3; // Columns in key switching matrix
    long w = 80; // Hamming weight of secret key
    long d = 0;
    long slb=0;  //Slots Lower Bound : minimum number of slots 
    long security = 62; // security parameter , number is directly proportional to the security.  
    /* Get a random number from whatever random source you have: /dev/random, 
    /dev/urandom, input by the user from the command line, or whatever*/
    ZZ seed;
    cout<<"seed=";
    cin>>seed;
    NTL::SetSeed(seed);

    ZZX G;
    m = FindM(security, L, c, p, d, slb, 0);
    FHEcontext context(m, p, r);
    buildModChain(context, L, c);
    G = context.alMod.getFactorsOverZZ()[0];

    //key generation
    FHESecKey secretKey(context);
    const FHEPubKey& publicKey = secretKey;
    secretKey.GenSecKey(w);
    EncryptedArray ea(context, G);
	
   //storing public key in file
    ofstream myfile;
     myfile.open ("~your path/HElib-master/src/public_key.txt");
     myfile <<publicKey;
     myfile.close();
	
    //storing secret key in file	
    ofstream myfile1;
     myfile1.open ("~your path/HElib-master/src/secret_key.txt");
     myfile1 <<secretKey;
     myfile1.close();
	
    //storing context in file	
    ofstream myfile3;
     myfile3.open ("~your path/HElib-master/src/Context.txt");
     myfile3 <<context;
     myfile3.close();
	
   //client data	
   vector<long> v2;
    for (int i = 0; i < ea.size(); i++) {
        v2.push_back(1);
    }
   cout<<v2<<endl;
   Ctxt ct1(publicKey);
    ea.encrypt(ct1, publicKey, v2);
	
   //storing encrypted client data in file
    ofstream myfile2;
    myfile2.open ("~your path/HElib-master/src/client_data.txt");
    myfile2 <<ct1;
    myfile2.close();
	 
	}
```
Once again thank you so much for your valuable time and consideration.

**Comment by shaih** [comment]
I don't know, but it looks like a bug. One thing that's suspicious is that you had to disable the error message in `seekPastChar`, this may indicate that the server gets some garbage.

To help in debugging, can you add the following to the very beginning of `FHESecKey::ImportSecKey(....)` (in 'FHE.cpp'):
```
{
  ZZX poly;
  skey.toPoly(poly);
  cout << "secret key is "<<poly<<endl;

  if (sKeys.empty()) { // 1st secret-key, generate corresponding public key
  // ... continue as before
```
Then you can see if the client and server really print out the same thing, is it the all-0 polynomial, etc.

Thanks, -- Shai

**Comment by AbhishekNalamothu** [comment]
I added above lines to FHE.cpp. I got same polynomial (which has 0s and -1s) after executing **client_sample_kg.cpp** and **Sk_determining.cpp** (I compared both polynomials by using checksum). 
 
However, I got different secret keys after executing **client_sample_kg.cpp** and **Sk_determining.cpp**(I compared both secret keys by using checksum). Even though they both are different, secret key which is generated on server side (using _Sk_determining.cpp_) is able to decrypt the data. 

Thank you so much Shai for your responses. 
Sincerely,
Abhi.

**Comment by AbhishekNalamothu** [comment]
Hi Shai, Greetings! 
I created public key (PK), context, secret key(SK) and encrypted client's data (ECD) in different environment. I imported PK, context, and ECD to my machine, and tried brute force on hamming weight parameter using **Sk_determining.cpp.** I am still able to decrypt the ECD. 

Could you please suggest me (if possible run those scripts) a way to make my programs more resistant to attacks?

Thank you for your valuable time and consideration. 
Sincerely,
Abhi.

**Comment by fionser** [comment]
@AbhishekNalamothu @shaih 
* After looking into the `sampleHWT` function in "Numb.cpp" ;
It seems HElib use `lrand48()` as the PNG. So using "NTL::SetSeed" wouldn't work.
* We need to use "srand48(int)" to init the state
* Note that `lrand48` is not cryptographically strong, we might better to change it to NTL's interface.

**Comment by AbhishekNalamothu** [comment]
Thank you so much @fionser ! I will look into the points you mentioned. If possible, could you please run the above 4 scripts, and check whether you can attack using 4th script- **Sk_determining.cpp.**

Once again thank you for your time and consideration.

**Comment by fionser** [comment]
@AbhishekNalamothu Before `GenSecKey`, for now, using `srand48(NTL::RandomWord());` would give you random-look-like secret key. so the `SK_determining.cpp` would not work.

**Comment by AbhishekNalamothu** [comment]
Thank you so much @fionser and @shaih  for your quick responses. ```SK_determining.cpp``` is not working (it is unable to decrypt). ```srand48(NTL::RandomWord());``` fixed my problem.
We can close this issue.

**Comment by fionser** [comment]
@AbhishekNalamothu You can check out my newest [pull request](https://github.com/shaih/HElib/pull/242) which changes the PNG to NTL::RandomWord, so that NTL::Seed would work.

**Comment by shaih** [comment]
My apologies, I'm working on a different branch that doesn't have lrand anymore, and forgot that master still has it. I expect to merge many changes to master in about a month, in particular better routines for sampling stuff.

**Comment by AbhishekNalamothu** [comment]
No problem @shaih. I will look into new pull request @fionser.
