### ISSUE TITLE
Can I use vector<Ctxt>?

### ISSUE THREAD

**Issue by AmekiKyou** [shaih/HElib#241]
I noticed that in Test_IO.cpp or Test_General.cpp you are using ```EncryptedArray```.

I want to read in some discrete ciphertext, and do calculations on them separatedly. I think maybe I can use ```vector<Ctxt>```. Is ```vector<Ctxt>``` valid?

```
  ifstream fdb("../data/data.enc.bin", std::ios::binary);
  int tot=0;
  string temp;
  vector<Ctxt> ciphers;
  while (fdb>>temp){
    ++tot;
    fdb>>temp;
    Ctxt recmask(publicKey);
    fdb>>recmask;
    //Do something on recmask
    ciphers.push_back(recmask);
    for (int i=0;i<6;++i) fdb>>temp;
  }
  fdb.close();
```

Because I want to shuffle the vector ```ciphers``` afterwards. I do not know whether EncryptedArray can do this or not.

**Comment by fionser** [comment]
quick response, EncryptedArray is NOT equals to vector<Ctxt>, 
You can init vector<Ctxt> like this `std::vector<Ctxt> ctxts(10, Ctxt(publicKey));` using the `publicKey` instance.

**Comment by AmekiKyou** [comment]
Thanks fionser! I have completed my task with vector<Ctxt>

**Comment by fionser** [comment]
@AmekiKyou plz close  the issue, if your problem is fixed.
