### ISSUE TITLE
Right way to add ciphertexts of different modulo values

### ISSUE THREAD

**Issue by shrram12** [shaih/HElib#258]
I am converting an AES encrypted ciphertext to a homomorphic ciphertext using homomorphic evaluation of the decryption function. This is performed with a value of p=2. I have another ciphertext that is homomorphically encrypted with a value of p=257. I want to subtract the two values and want the resulting value to homomorphically encrypted with p=2. It would be great if someone can let me know what is the right way to achieve this !

**Comment by shaih** [comment]
This is not supported, and I'm not sure it ever will. With very few exceptions(*), the only way we know how to switch from one plaintext modulus to another is via bootstrapping. Moreover, such "cross plaintext space" bootstrapping is much more complicated than then normal one, in fact I don't think that anyone has ever worked out a method of doing it that would be efficient enough to be useful. This is an interesting open research question, if anyone want to work on it.

(*) The only exception to the above is that we can switch from plaintetx space p^e1 to p^e2, with the same prime p but different exponent.

**Comment by shrram12** [comment]
Thank you for the quick response ! 

I have a follow question, non related to this question..  My understanding wrt homomorphic evaluation of AES decryption circuit is that, the client has to homomorphically encrypt the AES key once and share the homomorphically  encrypted AES key with the server . The server will then be able to transform the AES encrypted data to homomorphic encrypted data by evaluating the decryption circuit. In this process, what is the right way for the client to transmit or share the homomorphic encrypted AES key with the server ?

**Comment by shaih** [comment]
I'm not sure I understand what you are asking. You share it just like you would any other FHE-encrytped data: Use either binary-IO or ASCII-IO routines to serialize the context, public key, and ciphertexts, then send them to the server, and deserialize on the server side. See `Test_IO.cpp` and `Test_Bin_IO.cpp` for examples).

**Comment by shrram12** [comment]
Thank you, I am new to HElib and hence I was exactly looking for this ..
