### ISSUE TITLE
Using non-default values for c in finding m

### ISSUE THREAD

**Issue by datascale** [shaih/HElib#261]
Can I use the non-default values for c, for example c = 5, and find a m corresponding to certain security level k and depth L?

What exactly is happening when I do this?

I see I get smaller m values with larger c, hence faster computations

However, I think the ciphertext file size increases too.

Thank you.

security level: 112, p=2, r =32, w -64, L =9

when c =3,
m generated:8191
number of slots: 630

when c = 5,
m generated:10261
number of slots: 330

**Comment by shaih** [comment]
bigger values of c means that the evaluation keys are getting larger, but the cipehrtext should not. For a fixed security level and fixed values of m and L, the size of the largest modulus that we deal with gets smaller with larger values of c, hence you get more security. The expression is very roughly 

  largest-modulus-size-with-some-value-of-c = L * something * (1 + 1/c)

For a fixed security level, the value of m should be smaller, not larger as in your example.

You can see a description of what actually happens in Section 3.1.6. in the [HElib design document](http://shaih.github.io/pubs/he-library.pdf): c is the number of digits that we use in re-linearization (it is denoted n in that section).

**Comment by datascale** [comment]
Thank you, @shaih for the explanation. 

Yes, the examples I gave were flipped by accident. The first parameters were for c = 5 and the second were for c = 3.
