### ISSUE TITLE
How to pass <long> array to EncryptedArray.encrypt(ctxt,publickey,ptxt)

### ISSUE THREAD

**Issue by Foram16** [shaih/HElib#267]
**Technical Lead:** 
**Expected Effort (Days, Weeks or Months):** 
**Expected Start Date:**
**People or Skills Needed:** 

**Brief Description:**

In order to encrypt a <long> array using EncryptedArrayBase class's function encrypt(Ctxt& ctxt, const FHEPubKey& pKey, const vector< long >& ptxt) , i tried the following:

`   
    FHEPubKey publicKey(context);
    pubKeyFile >> publicKey;         //read public key from the file
    
    vector<long> val,u(s*x);        
    Byte result[s];
    for (i= 0; i < s*x; i++) {
     u[i] = rand()%2; 
    cout<<" "<<u[i];  	
    }    
//convert binary to long
    for (i=0; i<s; i++)
    {
        for (j=0; j<x; j++){
            result[i][x-j-1]=u[i*x+j];
        }
        val.push_back(result[i].to_ulong());
    }
    std::unique_ptr<EncryptedArray> ea;
    ea.reset(new EncryptedArray(context));   
    Ctxt encU(publicKey); 
    ea->encrypt(encU, publicKey, val);
`

but I get error : 
> encrypt_x: PAlgebra.cpp:523: void >PAlgebraModDerived<type>::embedInSlots(PAlgebraModDerived<type>::RX&, const >std::vector<typename type::RX>&, const MappingData<type>&) const [with type = PA_zz_p; >PAlgebraModDerived<type>::RX = NTL::zz_pX; typename type::RX = NTL::zz_pX]: Assertion >`lsize(alphas) == nSlots' failed.
>Aborted (core dumped)

I'm not sure what am doing wrong. Also what is the purpose of nslots?
parameters: s=256, r=32,p=2,m=269c=2,d=1.k=128

**Comment by fionser** [comment]
You need to set the length of vector be the exact same number of `EncryptedArray::size()`.

**Comment by Foram16** [comment]
Thank you. Yes it works.
So only if M is set to a higher value it will accept more than s slots?
getNSlots() function returns the dimension of the hypercube, what space here represents the hypercube?

**Comment by fionser** [comment]
* The number of slots come from a mass math, i.e., 'slots = phi(m) / multiplicative_order(m, t)'; Thereby, given `m`, HElib tries hard to find a `t` that can provide `s` slots. Usually, it is impossible to have exact `s` slots, depending on the combination of `m` and `s`.
* Hypercube is even much more complicated to understand, which leads to the rotation operation in HElib.

**Comment by Foram16** [comment]
Thank you.
So if I'm using a smaller M value to encrypt a <long int> vector of length, closer to, but less than m by bypassing the EncryptedArray.encrypt() and directly using publickey.encrypt() form FHE, **will it lead to reduced security**?   As number of plaintext slots would essentially be a small value.....  
Is it essential to use FindM() to identify suitable M value. Will smaller values lead to any security issues.

**Comment by fionser** [comment]
Basically, parameters that connect with security are 'm' and level 'L'.
You can use FHEcontext::securityLevels() to see an estimation of the security level.

**Comment by Foram16** [comment]
I could not locate FHEcontext::securityLevels() in the Library.

**Comment by fionser** [comment]
@Foram16 https://github.com/shaih/HElib/blob/master/src/FHEContext.h#L186

**Comment by Foram16** [comment]
Thank you very much.

**Comment by Foram16** [comment]
Sorry to re-open this issue, I did not want to create another issue. 
What is the unit of the value returned by  FHEcontext::securityLevels() also what does it represent?
what I understood is it depends on 'm' and 'L' . k- known as security parameter does not alter this parameter. Than you in advance.

**Comment by fionser** [comment]
1. It returns the _estimated_ security level. 
2. The math is very clear as it implemented in FHEcontext::securityLevel(). Basically, 
>>>
   To get k-bit security we need N>log(Q0/sigma)(k+110)/7.2, i.e. roughly  N > (L+1)*pSize*(1+1/c)(k+110) / 7.2

**Comment by fionser** [comment]
N is phi(m) i.e the length of polynomial .
FindM should return a as small as possible m that provides _at least_ k bit security.
