### ISSUE TITLE
is there an interface/function for and/or/xor operations for encrypted number?

### ISSUE THREAD

**Issue by bear1988520** [shaih/HElib#270]
**Technical Lead:** 
**Expected Effort (Days, Weeks or Months):** 
**Expected Start Date:**
**People or Skills Needed:** 

**Brief Description:**

is there an interface/function for and/or/xor operations for encrypted number?
Thanks

**Comment by bear1988520** [comment]
> **Technical Lead:**
> **Expected Effort (Days, Weeks or Months):**
> **Expected Start Date:**
> **People or Skills Needed:**
> 
> **Brief Description:**
> 
> is there an interface/function for and/or/xor operations for encrypted number?
> Thanks

because I am working on binary calculation for encryted number, the bit operations is necessary for me.

**Comment by shaih** [comment]
If you set p=2 as the plaintext space (when initializing a new FHEcontext) then + will be XOR and * will be AND, and you can realize OR as x+y-xy
