### ISSUE TITLE
getSet4Size: no matching Index found, likely decryption error

### ISSUE THREAD

**Issue by boev** [shaih/HElib#279]
Hi folks,

I have a small prototype using HElib and code is working correctly with older version of the library, but produces the output below when I try any computation using the current version of HElib. What does this error mean in general?

Output:
....
getSet4Size: no matching IndexSet found, likely decryption error
getSet4Size: no matching IndexSet found, likely decryption error
Ctxt::bringToSet called with capacity=-4.29614, likely decryption error
getSet4Size: no matching IndexSet found, likely decryption error
getSet4Size: no matching IndexSet found, likely decryption error
Ctxt::bringToSet called with capacity=-4.29614, likely decryption error
Ctxt::bringToSet called with capacity=-23.6773, likely decryption error
getSet4Size: no matching IndexSet found, likely decryption error
getSet4Size: no matching IndexSet found, likely decryption error
getSet4Size: no matching IndexSet found, likely decryption error
...

**Comment by shaih** [comment]
the recent code update is not backward compatible. In particular the 'L' parameter to `buildModChain` has changed from #-of-levels to #-of-bit. Roughly it means that you need to multiply whatever was there before by 30 or so (but some experimentation is needed to find the right number).

At some point we plan to provide tools to help you determine the number of bits to use in that call.

**Comment by boev** [comment]
Thanks for the quick reply :) Yes, I saw in the chages.md that things have changed. I have indeed tried setting L to a higher value (x30) but I seem to get exactly the same result. Fresh ecnryptions are correct but as soon as I do even one operation => this error. I will try to figure out what am I doing wrong by looking at HElib's test sources.

This is output from my HELib parameters:
Initializing HElib Context...
Finding M...
*** Bound N=21112, choosing m=27305, phi(m)=21168
 R=round undefined, p=2, r=1, d=0, c=3, k=80, w=64, L=600, m=27305, isBootstrappable=0, Security level=69.5343
m = 27305, p = 2, phi(m) = 21168
  ord(p)=28
  generator 6 has order (== Z_m^*) of 126
  generator 781 has order (== Z_m^*) of 6

security=69.5343
# ctxt primes = 11
# bits in ctxt primes = 614
# special primes = 4
# bits in special primes = 235
G = [1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 1 0 1 1 0 0 0 0 0 1]
Number of slots: 756
HElib Wrapper initialized successfully!

**Comment by shaih** [comment]
Thanks, let me know what you find. This new version was very lightly tested so it may very well be a bug

**Comment by boev** [comment]
I do not have this problem with the current version. Maybe there was a problem with my other parameters. I also started using the parameter table in Test_binaryArith.cpp when dealing with bit-per-bit encryption. Very helpful.
