### ISSUE TITLE
HElib segfault 

### ISSUE THREAD

**Issue by AndyLavr** [shaih/HElib#282]
commit 6331712c57e79add52aba3c51469c2da3b597622

[ +16,248473] Test_General_x[25558]: segfault at 8 ip 000055b1377e1119 sp 00007ffe4769d260 error 4 in Test_General_x[55b13779b000+d7000]
[  +0,000017] Code: 0f 85 ea 03 00 00 48 8d 05 c4 6b 0c 00 48 89 44 24 40 e8 3a b5 fd ff 49 8b 75 00 c6 44 24 50 01 48 89 44 24 48 48 8b 44 24 10 <48> 8b 78 08 e8 ce d4 fe ff 84 c0 0f 84 33 05 00 00 48 8b 44 24 10

**Comment by boev** [comment]
Hi, I have also noticed this on Monday. I think the maintainers know about it and probably need time to fix it. Here is a more detailed output from valgrind, hopefully it would help resolving the error:

/HElib/src$ valgrind --leak-check=no ./Test_General_x R=1 k=10 p=2 r=2 noPrint=1

``
==25810== Memcheck, a memory error detector
==25810== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==25810== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
==25810== Command: ./Test_General_x R=1 k=10 p=2 r=2 noPrint=1
==25810== 
vex amd64->IR: unhandled instruction bytes: 0xF3 0x4C 0xF 0x38 0xF6 0xF 0x48 0x8D
vex amd64->IR:   REX=1 REX.W=1 REX.R=1 REX.X=0 REX.B=0
vex amd64->IR:   VEX=0 VEX.L=0 VEX.nVVVV=0x0 ESC=0F38
vex amd64->IR:   PFX.66=0 PFX.F2=0 PFX.F3=1
==25810== Invalid read of size 8
==25810==    at 0x44A81F: FHESecKey::Decrypt(NTL::ZZX&, Ctxt const&, NTL::ZZX&) const (FHE.cpp:887)
==25810==    by 0x4865F9: decryptAndPrint(std::ostream&, Ctxt const&, FHESecKey const&, EncryptedArray const&, long) (debugging.cpp:66)
==25810==    by 0x45BB68: Ctxt::multLowLvl(Ctxt const&, bool) (char_traits.h:320)
==25810==    by 0x45D29A: operator*= (Ctxt.h:356)
==25810==    by 0x45D29A: Ctxt::multiplyBy(Ctxt const&) (Ctxt.cpp:1248)
==25810==    by 0x410D5B: TestIt(long, long, long, long, long, long, long, long, long, NTL::Vec<long> const&, NTL::Vec<long> const&) (Test_General.cpp:155)
==25810==    by 0x40EC26: main (Test_General.cpp:339)
==25810==  Address 0x8 is not stack'd, malloc'd or (recently) free'd
==25810== 
==25810== 
==25810== Process terminating with default action of signal 11 (SIGSEGV)
==25810==  Access not within mapped region at address 0x8
==25810==    at 0x44A81F: FHESecKey::Decrypt(NTL::ZZX&, Ctxt const&, NTL::ZZX&) const (FHE.cpp:887)
==25810==    by 0x4865F9: decryptAndPrint(std::ostream&, Ctxt const&, FHESecKey const&, EncryptedArray const&, long) (debugging.cpp:66)
==25810==    by 0x45BB68: Ctxt::multLowLvl(Ctxt const&, bool) (char_traits.h:320)
==25810==    by 0x45D29A: operator*= (Ctxt.h:356)
==25810==    by 0x45D29A: Ctxt::multiplyBy(Ctxt const&) (Ctxt.cpp:1248)
==25810==    by 0x410D5B: TestIt(long, long, long, long, long, long, long, long, long, NTL::Vec<long> const&, NTL::Vec<long> const&) (Test_General.cpp:155)
==25810==    by 0x40EC26: main (Test_General.cpp:339)
==25810==  If you believe this happened as a result of a stack
==25810==  overflow in your program's main thread (unlikely but
==25810==  possible), you can try to increase the size of the
==25810==  main thread stack using the --main-stacksize= flag.
==25810==  The main thread stack size used in this run was 8388608.
*** multLowLvl, just before modDown ==25810== 
==25810== HEAP SUMMARY:
==25810==     in use at exit: 261,242,557 bytes in 65,087 blocks
==25810==   total heap usage: 2,459,563 allocs, 2,394,476 frees, 6,123,532,502 bytes allocated
==25810== 
==25810== For a detailed leak analysis, rerun with: --leak-check=full
==25810== 
==25810== For counts of detected and suppressed errors, rerun with: -v
==25810== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
Segmentation fault

``

**Comment by AndyLavr** [comment]
Source code from 20190215, problem solved.
Build fine, all tests good. Big thanks.
