### ISSUE TITLE
how can I put the plaintext into the vector<ZZX>

### ISSUE THREAD

**Issue by ldwaiwai** [shaih/HElib#41]
I want to know how can I put the plaintext into the variable v1 when I concept : vector<ZZX> v1.
I know we can do that like this ea.random(v1).Is there any different way?

**Comment by rohitkhera** [comment]
I am a little confused by a statement in @TomMD's guide - 

"Folks wanting to see 2+2=4 should set p to something that matches their desired domain, such as 257 to obtain 8 bit Ints"

Should it not be the case that obtaining 8 bit integer arithmetic can be achieved by embedding F_(2^8) into the "embedded plaintext" field for the slots. This could be achieved with p=2 (and r=1) by selecting m such that the m'th cycotomic polynomial splits mod 2 into L distinct factors of degree d such that d is divisable by 8. Or is it neccessary to select p = 257 for this?

**Comment by shaih** [comment]
You can of course use F_{2^8} for your plaintext space as you said (indeed, this is what we do in our homomorphic-AES implementation). But then you get F_{2^8} arithmetic, for example in this case you have 1+1=0.

To get "native" arithmetic operations over larger integers, your p^r must be larger.
