### ISSUE TITLE
What is the meaning of "Size of the constant"

### ISSUE THREAD

**Issue by fionser** [shaih/HElib#47]
I am reading the design doc of HElib. I noticed that the ciphertext-constant multiplication/addition methods have a default parameter "size" which refers the size of the operand constant. But I am very not sure what value should I set. For example, I want to multiply just 0/1 binary, what is the "Size of the constant" should be? Thank you!

**Comment by shaih** [comment]
The short answer is that if you don't know what it is then it is safe to leave it unspecified (which would assign a reasonable default value).

The longer answer is that a constant is not just 0/1 but actually a vector of 0-1 values, and that vector is encoded by some polynomial. The "size" parameter is some approximation of the squared the Euclidean norm of the coefficient vector of that polynomial.
