### ISSUE TITLE
context.rcData.e value 

### ISSUE THREAD

**Issue by alphacristi** [shaih/HElib#51]
First i generate context and print out the value of  context.rcData.e , which is for example 13.
When i  save the context to file and try to read it again the value of context.rcData.e is always 0.
Anyone knows what could be the problem ?
Thank you.

Code for saving&loading context : 

void saveContextAndSecretKey(const char *fname, FHEcontext& context, FHESecKey& secretKey)
{	ofstream str (fname);
	if (!str.is_open()){
                cout << "IO error " << endl;
		return;
                }
	writeContextBase(str, context);
	str << context;
	str << secretKey;
	str.close();
}

void loadContextAndSecretKey(const char *fname, FHEcontext*& context, FHESecKey*& secretKey)
{	ifstream str (fname);
	if (!str.is_open()){
		cout << "IO error " << endl;
		return;
                }
    unsigned long m, p, r;
    readContextBase(str, m, p, r);
    context = new FHEcontext (m, p, r);
    str >> *context;
   secretKey = new FHESecKey(*context);
   str >> *secretKey;
   str.close();
}

**Comment by shaih** [comment]
Yes, this is a bug, I forgot to update the context I/O woutines to handle the bootstrapping data. I will fix it soon, until then, a workaround is to call the makeBootstrappable method again (assuming that you have the mvec vector that it needs as its first argument).

**Comment by alphacristi** [comment]
Thank you !

**Comment by shaih** [comment]
The new version of HElib from March 27, 2015 fixes this issue.
