### ISSUE TITLE
DNO_HALF_PRIME flag

### ISSUE THREAD

**Issue by fionser** [shaih/HElib#52]
I am confusing about the DNO_HALF_PRIME flag. 

For example, I need to evaluate depth `3` function and I set parameter `L = 3`, however it always failed because of too large noise(I guess). I read through the code (in `FHEContext.cpp buildModChain function`) and found this DNO_HALF_PRIME flag. 

I am wonder if I turn on the DNO_HALF_PRIME flag, how should I comprehend the parameter `L` in the `findM` function.In my comprehension this levels parameter `L` matters the security level a lot.

Thank you!

**Comment by shaih** [comment]
No, in principle there should not be any connection between the `NO_HALF_PRIME` flag and the `L` parameter. This flag is a low-level optimization, the rule of thumb is to use this flag on 32-bit machines and NOT use it on 64-bit machines.

A related setting is that of the data member `context.bitsPerLevel`. The rules are a little messy, especially on 32-bit machines (I should probably fix this at some point). For 64-bit machines the rules are as follows:

+ The default value is `context.bitsPerLevel=22`. to overwrite this default, just set `context.bitsPerLevel=[newval]` before calling `context.buildModChain(...)`

+ The default value of 22 should work for p^r=2 and m upto 20,000 or so. For larger p^r  and m you may need to increase it. A reasonable rule-of-thumb is to set

   ``context.bitsPerLevel = 14 + ceiling((log m)/2 + r*log p)``

  If you observe that your circuit consumes the levels too quickly (i.e., you get warning saying "already at lowest level"), you can try to increase `context.bitsPerLevel` and see if it helps.

+ When the `NO_HALF_PRIME` flag is set, then `context.bitsPerLevel` can be as large as the `NTL_SP_NBITS` constant in NTL (which is 30 on 32-bit machines and either 50 or 60 on 64-bit machines).

 If this flag is NOT set, then you need `context.bitsPerLevel <= NTL_SP_NBITS/2`. The library will not complain if you set it higher, but the behavior in terms of level consumption during the computation will be erratic. If you find that you need a larger value of `context.bitsPerLevel` then you should set the `NO_HALF_PRIME` flag.

This aspect of the library is quite hack-ish right now, it would be good if someone is willing to put some work in making the behavior a little less arbitrary.

**Comment by fionser** [comment]
Thank you for the response. 
Indeed, I am concerning about the security of this `bitsPerLevel` setting.
I found the formula in your works [Hom. AES](https://eprint.iacr.org/2012/099.pdf). Eq 17 in page 29 which is 
`N > (L (log(N) + 23 - 8.5)(k + 110) / 7.2`. 
(is that also the implementation details in the `findM` function?)  The `L` in this equation is the same parameter in HElib settings, am I right?
