### ISSUE TITLE
Multi-Threaded execution of Test_Timing_x

### ISSUE THREAD

**Issue by sameersave** [shaih/HElib#55]
I am working on an academic project and have to test the timings of all functions used in HE. Is there a way to test them in a multi threaded setup?

**Comment by fionser** [comment]
To test these functions in multithread environment, you have to setup the 
thread-safe mode for both NTL and HElib first.

In my case, ubuntu 14.04 with g++4.9 works.
But you have to build NTL with flag `NTL_THREADS=on`
and build HElib with flag `-DFHE_THREADs -DFHE_DCRT_THREADS`.

Multithreading programming, I recommend you to use the c++ standard library `include <thread>`.
Of course, you need to add library link `-pthread` when you build up your `main.cpp`
