### ISSUE TITLE
Is there anyway to use HElib to encrypt images

### ISSUE THREAD

**Issue by sameersave** [shaih/HElib#57]

**Comment by TomMD** [comment]
@sameersave With modern cryptography you can operate on anything that can be encoded as bits.  If you are unsure how to encode your image I suggest you find a programmer Q&A site.

Also please notice github issue trackers are not generally for questions but actual bug reports.

**Comment by sameersave** [comment]
@TomMD  thanks for your prompt reply. 
I apologize for using the provision for other than the intended use.
