### ISSUE TITLE
NTL 9.1.0 is not supported

### ISSUE THREAD

**Issue by bogdan-kulynych** [shaih/HElib#59]
Compilation errors arise when HElib is compiled using NTL 9.1.0

```
In file included from /usr/local/include/NTL/ZZ.h:20:0,
                 from NumbTh.h:34,
                 from DoubleCRT.h:21,
                 from FHE.h:24,
                 from EncryptedArray.h:25,
                 from EncryptedArray.cpp:19:
/usr/local/include/NTL/vector.h: In instantiation of ‘void NTL::conv(NTL::Vec<T>&, const NTL::Vec<S>&) [with T = NTL::ZZ; S = NTL::GF2]’:
/usr/local/include/NTL/vector.h:791:24:   required from ‘void NTL::conv(NTL::Vec<T>&, const NTL::Vec<S>&) [with T = NTL::Vec<NTL::ZZ>; S = NTL::Vec<NTL::GF2>]’
/usr/local/include/NTL/matrix.h:246:33:   required from ‘void NTL::conv(NTL::Mat<T>&, const NTL::Mat<S>&) [with T = NTL::ZZ; S = NTL::GF2]’
EncryptedArray.cpp:404:19:   required from ‘void EncryptedArrayDerived<type>::initNormalBasisMatrix() const [with type = PA_GF2]’
EncryptedArray.cpp:2124:16:   required from here
/usr/local/include/NTL/vector.h:788:25: error: ‘const class NTL::Vec<NTL::GF2>’ has no member named ‘elts’
    const S *ap = a.elts();
```

Therefore, instruction 'HElib requires NTL version 9.0.1 or _higher_' isn't up-to-date.

**Comment by victorshoup** [comment]
I think I see the problem.  I will have to make a small fix to NTL.  I'll try to get to it today or tomorrow.  In the meantime, best to stick with 9.0.1.  I guess the lesson is that I should really test NTL against helib before new NTL releases.

**Comment by victorshoup** [comment]
So I just uploaded a new version of NTL: v9.1.1, which fixes a bug I introduced in 9.1.0.
I didn't get a chance to test it against helib, but it does fix the problem that you ran into.

Could you try installing NTL 9.1.1 on your system and then try building helib against that?
Thanks!

**Comment by victorshoup** [comment]
Please let me know if that fixes all issues...

**Comment by bogdan-kulynych** [comment]
Yes, building against NTL 9.1.1 fixed the issue. Thanks!
