### ISSUE TITLE
key import from / export to string 

### ISSUE THREAD

**Issue by t-ghost** [shaih/HElib#64]
Hi!
Is there an easy way to import / export keys (secret and public) to / from string? I am currently using simple cout-streams to save the keys to a file, but reading them in again turns out problematic this way...

Have a nice weekend!

**Comment by shaih** [comment]
You can see examples of use in the ``Test_IO.cpp`` program

**Comment by t-ghost** [comment]
Thank you very much! It seems to be working! (currently still in testing)
