### ISSUE TITLE
About the Nslots

### ISSUE THREAD

**Issue by alinan8868** [shaih/HElib#71]
Hi everyone,
I'm instereted in Helib.I want to change the size of nslots,like nslots=8.
how should I set it up?
Thanks.

**Comment by fionser** [comment]
You need to figure out the underlying math about the number of slots.
`#slot = phi(m) / order(p, m)`, here `phi()` is the Euler's function, and `order(p,m)` is the multiplicative order of `p` given `m`.

**Comment by alinan8868** [comment]
Thank you for your help.
If I make the nSlots=8,Is it also security?and could you give me the m,p to get nSlots=8 ,if you have time.
Thanks :)

**Comment by fionser** [comment]
security is the function of `m` and `L` has nothing with the number of slots

**Comment by alinan8868** [comment]
Thank you very much:)
