### ISSUE TITLE
How Send Ctxt?

### ISSUE THREAD

**Issue by GiuliaDro** [shaih/HElib#75]
For my project I need to use a socket to send a ctxt or an encrypt array form a server to anther.
Is there any functionality to do that?

**Comment by ssmiler** [comment]
The easiest way is to write a ctxt to a file and send the file.
More generally, HElib is a low-level library. High-level constructions as you need must be coded by yourself.

**Comment by qdm12** [comment]
Hi there, I am working on something similar. I would like to implement a server/client with HElib but I really don't have a clue how to save/store an EncryptedArray object for example. Is there any built-in serialization or anyone has any idea how this could be done, without breaking everything ? Thank you in advance !

**Comment by shaih** [comment]
You can find examples of writing and reading ciphertexts and keys in the file `Test_IO.cpp`
