### ISSUE TITLE
Function Cannot return an instance of EncryptedArray

### ISSUE THREAD

**Issue by lepro09** [shaih/HElib#86]
I' m running the following code:

      `EncryptedArray  GetEA()  {
            FHEcontext context(m, p, r);

	// initialize context

	buildModChain(context, L, c);

	// modify the context, adding primes to the modulus chain

	G = context.alMod.getFactorsOverZZ()[0];

        EncryptedArray testEa(aContext, G);

         return testEa;
           }`
The problem is, the returned EncryptedArray doesn't content the same value as the array in the function. The Encrypted array in the function  is deleted before the return call. 
Does it give any way to solve it?

**Comment by matlink** [comment]
Try to declare your EncryptedArray before entering the function.

**Comment by ssmiler** [comment]
Or create EncryptedArray object dynamically inside function and return a pointer.

**Comment by lepro09** [comment]
@matlink  i do declare my EncryptionArray before
@ssmiler the encrypteArray looks like:
`class EncryptedArray {
private:
  PAlgebraMod& alMod;
  cloned_ptr<EncryptedArrayBase> rep;`
 It returns the encrypted array. The  value of alMod is deleted when the scope is changed, for example tempting to use the returned EncryptedArray in another function.  Any other idea?

**Comment by lepro09** [comment]
@matlink @ssmiler  Thanks alot guys. I solved the problem.
