### ISSUE TITLE
Bit-sliced AES implementation

### ISSUE THREAD

**Issue by axelmma** [shaih/HElib#87]
I'm currently working on a bit-sliced AES implementation but I cannot afford to assign one ciphertext per bit ( memory cost is too big ), especially when i'm encrypting the round keys.
I did manage to reduce the memory cost using a ciphertext per round key.

For compatibility purpose, I also tried to use a single ciphertext to represent the AES state.
However, for the SubBytes operation, I still need to break the encrypted state (all the bits are stored into a single ciphertext ) into several ciphertexts ( one ciphertext per bit ). 
So far, nothing i've tried has worked. 

Does anyone have any ideas how to do that ?

In advance, many thanks.

**Comment by ssmiler** [comment]
Take a look at the "byte-sliced" implementation of AES described [here](http://eprint.iacr.org/2012/099). GF(256) plaintext space is used instead of GF(2), which increases performance.

**Comment by axelmma** [comment]
Thank you for your answer. 
I need to keep working in GF(2), even if an other plaintext space increases performance. 
My main problem is really to figure out how to split a ciphertext into several ones. In other words, I need to create a new ciphertext for each original "ciphertext slots".
 
For example : 
`//Suppose that FullEncryptedState encrypts a vector<long> representing each state bits`
`Ctxt FullEncryptedState(publicKey);`
 `vector<Ctxt> DividedEncryptedState;`
 `Ctxt` `tmpCtxt(publicKey);`
 `DividedEncryptedState.resize(nslots,Ctxt(ZeroCtxtLike,tmpCtxt));`

`for (int i = 0 ; i < nslots ; i ++ ){`
         `DividedEncryptedState[i] = FullEncryptedState[i];` 
`}`

Of course it doesn't work. I got an error : no match for 'operator[ ]' ( operand types are 'Ctxt' and 'int').
This is what i need to figure out..

**Comment by ssmiler** [comment]
I can see two solutions for your case:
(1) Create a 'selector' polynomial with value one in slot zero. On a ciphertext apply `EncryptedArray::rotate` to move a slot into position zero and multiply the obtained ciphertext with the selector polynomial. Do this for each input ciphertext slot and you'll obtain a ciphertext per slot.
(2) You can also execute the GF(256) version of AES and afterwards extract a ciphertext for each bit of the AES state. As GF(2) is a sub-field of GF(256), even if your plaintext space will always be GF(256) you'll be able to perform operations in GF(2). You can do this using linear transformation methods `applyLinPoly*` defined in `EncryptedArray.h`. See http://eprint.iacr.org/2015/1199 for more details.

**Comment by axelmma** [comment]
Great ! Thanks a lot !
