### ISSUE TITLE
Can I compute inner product over encrypted vectors using packing?

### ISSUE THREAD

**Issue by qhyhyl** [shaih/HElib#90]
Suppose there is two n-length vectors **a** and **b** and I want to compute Enc<**a**, **b**> (Enc() means encryption of). 
The naive way is to encrypt each a_i and b_i (i =1, 2, ..., n) and then do the homomorphic mul and add over these ciphertexts. But I was wondering whether I can use the ciphertext packing techniques to improve the efficiency.
I know I can put a_1, a_2, ... , a_n in one EncryptedArray ea_a and put b_1, b_2, ..., b_n in another EncryptedArray ea_b. And then I can get Enc(a_1 * b_1), Enc(a_2 * b_2), ..., Enc(a_n * b_n) by SIMD. But how can I add these items together to get the inner product result?

**Comment by ssmiler** [comment]
Rotate ciphertext slots and add ciphertexts, something like: sum_i(rotate(ctxt,i)) where ctxt = ctxt_a * ctxt_b.

**Comment by shaih** [comment]
If `a, b` are each one packed ciphertext, then first compute their point-wise product and then sum the result (using an EncryptedArray object):
```
  a.multiplyBy(b);
  ea.totalSum(a);
```
