### ISSUE TITLE
secure parameters for p=2, m=1  encryption that supports bootstrapping ?

### ISSUE THREAD

**Issue by mohakamo** [shaih/HElib#91]
I'm looking for secure parameters for 

p=2, m=1  encryption that supports bootstrapping.

In Test_Bootstrapping.cpp there are examples with m>1023
I can use this with wasting space that is not good as we know 

Also, I just wonder if smaller m means faster bootstrapping?

Thanks alot.

**Comment by shaih** [comment]
The parameter m is related to security, and typically needs to be in the few thousands. You can use smaller values of m for testing/debugging purposes, but it must be m>1, and it must be co-prime to p (the plaintext-space modulus).
