### ISSUE TITLE
Compute 'greater' (>) comparison on two ciphertexts

### ISSUE THREAD

**Issue by lepro09** [shaih/HElib#95]
Hey Guys,
I' m trying to compute comparison on two ciphertexts.  The Modulo space is 2. It works for equal Comparison (==), but not for greater (>).
i tried : `ct1 *= ct2;
 ct1 += ct2;
` but it doesn't work.  Any idea? 
In fact, the question is how can binary numbers can be added|subtrated|multiplied to simulate 'greater'( > ) comparison.
Thank. :)

**Comment by shaih** [comment]
What do you mean by > when the plaintext space is 2? If a,b are bits then you can only have a>b if a=1 and b=0, is this really what you want to check? In that case you can use a*(1-b) as follows:

```
  ct2.addConstant(to_ZZ(1)); // compute b+1, which is the same as 1-b modulo 2
  c1 *= c2;
```

**Comment by lepro09** [comment]
i mean, a and b are 4 bits length binary numbers and stored in vectors. These vectors are encrypted in two ciphertexts. I want to use the ciphertexts to determine if a > b or not.
Your idea sounds good, but i get different outputs depending on the binary numbers chosen. For example:  `ct1 = Encrypt(1001); ct2 = Encrypt(1000);
// the reulst is 0001` 
`ct1 = Encrypt(1010); ct2 = Encrypt(0111)
// the result is 1000`
Should i care about something else?

Thank :)

**Comment by shaih** [comment]
You need to first figure out a binary circuit that computes the bit that you want. Once you know what this circuit is, you can implement it homomorphically, using +, * and shifts/rotations (all of which are supported by HElib).

The details should be easy to work out, but note that there is more than one way of doing it and some ways are better than others.
