### ISSUE TITLE
Multiplication in loop returns wrong result

### ISSUE THREAD

**Issue by lepro09** [shaih/HElib#96]
Hey guys,

i'm trying to build a product of many ciphertexts in a loop, but the result is already wrong after the second iteration. Here is the source: 
```
    Ctxt *temp;
	Ctxt *finalCtxt;
         int j = 8;
	finalCtxt = new Ctxt(*encryption_of_1);
       for (i = 0; i < j; i++)
	{
               // current ciphertexts
		temp = new Ctxt(ct_x[i]);
		temp->addCtxt(ct_y[i]);
		temp->addCtxt(*encryption_of_1);

		vector<long> res_0;
		ea.decrypt(*temp, secretKey_Prover, res_0);

		vector<long> res;
		ea.decrypt(*finalCtxt, secretKey_Prover, res);
		
		*finalCtxt *= *temp;
		
	}
	return *finalCtxt;
```
Any idea? Should i change somtething in the initialisationsparameters?
Here are my initialisationparameters:

```
long m = 0, p = 2, r = 1; // Native plaintext space
	// Computations will be 'modulo p'
	//long L = 16;          // Levels
	long L = 4;          // Levels
	long c = 3;           // Columns in key switching matrix
	long w = 64;          // Hamming weight of secret key
	long d = 0;
	long security = 128;
	ZZX G;
	m = FindM(security, L, c, p, d, 0, 0);
```

Thanks :-)

**Comment by fionser** [comment]
your plaintext space is just `p^r = 2` so, you are doing operation on the domain `\{0, 1\}`, so ....

**Comment by lepro09** [comment]
so multiplying a ciphertext by 1 "` finalCtxt = new Ctxt(*encryption_of_1);`" should return the same ciphertext, but this is not the case from the second iteration. Once again, in the first iteration, everything is fine (`res_0 = res_1`), but from the scond iteration, the result is not correct(`res_0 =! res_1`), where the value encrypted in `finalCtxt` = `temp` which is `(*encryption_of_1)` also 1, before the operation `*finalCtxt *= *temp;`
```
        temp = new Ctxt(ct_x[i]);
        temp->addCtxt(ct_y[i]);
```
Ctxt(ct_x[i]), Ctxt(ct_y[i] encrypt the same value, so after the operations above `temp = 0`
Any other idea?

**Comment by shaih** [comment]
Im not sure what you are trying to do, but your code does not have any multiplies.
`
  finalCtxt = new Ctxt(*encryption_of_1)
`
is not a multiply-by-one, it is a copy constructor, copying the object pointed to by the pointer encryption_of_1.

I'm closing this topic, it seems to be some issues with C++ programing as opposed to anything specific to HElib.

**Comment by lepro09** [comment]
Forget about the pointer, try this code yourself and you will see:

Ctxt ct1(publicKey);
Ctxt ct2(publicKey);
vector<long> v1;
vector<long> v2;
vector<long> res;
for (int i = 0; i < ea.size(); i++) {
		if (i > 4 && i < 8)
		{	
			v1.push_back(1);
		}
		else
			v1.push_back(0);
	}
	ea.encrypt(ct1, publicKey, v1);

for (int i = 0; i < ea.size(); i++) {
		if (i > 4 && i < 7)
		{
			v2.push_back(1);
		}
		else
			v2.push_back(0);
	}
	ea.encrypt(ct2, publicKey, v2);
Ctxt ctProd = ct1;
for (int k = 0; k < 20; k++)
	{
		ctProd *= ct2;
		ea.decrypt(ctProd, secretKey, res);

		cout << "All computations are modulo " << p << "." << endl;
		for (int i = 0; i < res.size(); i++) {
                       // V1 is important only in the first iteration
			cout << v1[i] << " * " << v2[i] << " = " << res[i] << endl;
		}
	}
