### ISSUE TITLE
Can't compile since recent update of HElib

### ISSUE THREAD

**Issue by qdm12** [shaih/HElib#99]
Hi everyone,

I am using Debian and since the recent update using the newer version of NTL, I can't `make check` anymore or compile my code. It gives me the following compilation error when I try to `make check` in `HElib/src` :
![error](https://cloud.githubusercontent.com/assets/15654980/16208775/af33d87c-372b-11e6-9b86-82a9e09e62db.png)

I believe it is linked to the NTL library. I am using NTL 9.9.1 and it still does not work unfortunately.

Thank you in advance !

PS: You may also update the line "HElib requires NTL version 9.4.0 or higher, see http://shoup.net/ntl" in your makefile to NTL version 9.7.X I believe

**Comment by victorshoup** [comment]
Looks like a consistency issues. ntl header files and binaries are probably out of sync. Try rebuilding and reinstalling ntl, and then then helib 

qdm12 <notifications@github.com> wrote:
>Hi everyone,
>
>Since the update added 19 days ago, I can't `make check` anymore or
>compile my code. It gives me the following compilation error when I try
>to `make check` in the src folder of _HElib_ 
>![error](https://cloud.githubusercontent.com/assets/15654980/16208775/af33d87c-372b-11e6-9b86-82a9e09e62db.png)
>
>I believe it is linked to the NTL library. I am using NTL 9.9.1 and it
>still does not work unfortunately.
>
>Thank you in advance !
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/shaih/HElib/issues/99

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by qdm12** [comment]
I tried several times with `make uninstall` followed by a re-download + `make` and `make install` for ntl 9.9.1 as well as for 9.9.0 without success. A funny thing is that it works on cygwin on windows without problem.. I'll test it further and let you know. Anyway thanks for the quick answer!

**Comment by victorshoup** [comment]
What platform is this on? I'm not sure if I would trust ntl's make uninstall. I don't use or test it much. 

qdm12 <notifications@github.com> wrote:
>I tried several times with `make uninstall` followed by a re-download +
>`make` and `make install` for ntl 9.9.1 as well as for 9.9.0 without
>success. A funny thing is that it works on cygwin on windows without
>problem.. I'll test it further and let you know. Anyway thanks for the
>quick answer! 
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/shaih/HElib/issues/99#issuecomment-227294023

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by qdm12** [comment]
Yes you're right, there were indeed some NTL files remaining in /usr/local .. sorry for the question but thanks for the help !
